# Generated by Django 3.0.6 on 2020-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20200518_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
