# Generated by Django 3.0.6 on 2020-06-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-visits',)},
        ),
    ]
