# Generated by Django 3.0.6 on 2020-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.IntegerField(default=0),
        ),
    ]
